"""Crear modelos iniciales

Revision ID: 79c77e7cbe3e
Revises: 
Create Date: 2025-03-23 16:30:08.654491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79c77e7cbe3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'id_pet',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointment', 'id_service',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointment', 'id_veterinarian',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_appointment_id_appointment'), 'appointment', ['id_appointment'], unique=False)
    op.alter_column('medic_history', 'id_pet',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medic_history', 'id_veterinarian',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medic_history', 'vaccines',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('medic_history', 'observations',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('medic_history', 'documents',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('medic_history', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('medic_history', 'first_cons_date',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_medic_history_id_history'), 'medic_history', ['id_history'], unique=False)
    op.add_column('order_detail', sa.Column('id_orderdetail', sa.Integer(), nullable=False))
    op.alter_column('order_detail', 'id_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_detail', 'id_product',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_detail', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_detail', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_order_detail_id_orderdetail'), 'order_detail', ['id_orderdetail'], unique=False)
    op.drop_column('order_detail', 'id_ordetail')
    op.alter_column('orders', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_orders_id_order'), 'orders', ['id_order'], unique=False)
    op.alter_column('pet', 'id_owner',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_pet_id_pet'), 'pet', ['id_pet'], unique=False)
    op.alter_column('product', 'id_supplier',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'product_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_product_id_product'), 'product', ['id_product'], unique=False)
    op.create_index(op.f('ix_rol_id_rol'), 'rol', ['id_rol'], unique=False)
    op.create_index(op.f('ix_services_id_service'), 'services', ['id_service'], unique=False)
    op.create_index(op.f('ix_supplier_id_supplier'), 'supplier', ['id_supplier'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=60), nullable=True))
    op.alter_column('users', 'id_rol',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'u_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.drop_column('users', 'password_hashed')
    op.alter_column('veterinarian', 'name_vet',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('veterinarian', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('veterinarian', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('veterinarian', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('veterinarian', 'direction',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_veterinarian_id_veterinarian'), 'veterinarian', ['id_veterinarian'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veterinarian_id_veterinarian'), table_name='veterinarian')
    op.alter_column('veterinarian', 'direction',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('veterinarian', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('veterinarian', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('veterinarian', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('veterinarian', 'name_vet',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('users', sa.Column('password_hashed', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'u_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'id_rol',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_supplier_id_supplier'), table_name='supplier')
    op.drop_index(op.f('ix_services_id_service'), table_name='services')
    op.drop_index(op.f('ix_rol_id_rol'), table_name='rol')
    op.drop_index(op.f('ix_product_id_product'), table_name='product')
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('product', 'product_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('product', 'id_supplier',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_pet_id_pet'), table_name='pet')
    op.alter_column('pet', 'id_owner',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_orders_id_order'), table_name='orders')
    op.alter_column('orders', 'payment_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('orders', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('order_detail', sa.Column('id_ordetail', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_order_detail_id_orderdetail'), table_name='order_detail')
    op.alter_column('order_detail', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('order_detail', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_detail', 'id_product',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_detail', 'id_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_detail', 'id_orderdetail')
    op.drop_index(op.f('ix_medic_history_id_history'), table_name='medic_history')
    op.alter_column('medic_history', 'first_cons_date',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('medic_history', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('medic_history', 'documents',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('medic_history', 'observations',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('medic_history', 'vaccines',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('medic_history', 'id_veterinarian',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medic_history', 'id_pet',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_appointment_id_appointment'), table_name='appointment')
    op.alter_column('appointment', 'id_veterinarian',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointment', 'id_service',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointment', 'id_pet',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
